kind: pipeline
type: docker
name: ci

steps:
  - name: hw
    image: alpine
    commands:
      - echo "hello world"

  - name: cppcheck
    image: alpine
    commands:
      - apk --no-cache add make cppcheck g++
      - make test
