kind: pipeline
type: docker
name: ci

steps:
  - name: linefeed-and-encoding
    image: docdee/filecheck
    commands:
      - (! find . -maxdepth 1 -name "*.*" -not -type d -exec file "{}" ";" | grep "CRLF\|CR")
      - (find . -maxdepth 1 -name "*.*" -not -type d -not -name "*.png" -not -type d -exec isutf8 "{}" "+")

  - name: markdownlint-cli
    image: docdee/mdlint
    commands:
      - markdownlint README.md CHANGELOG.md

  - name: cppcheck
    image: docdee/cppcheck
    commands:
      - cppcheck --version
      - cppcheck --enable=warning,performance,portability,style --language=c --std=c99 --check-level=exhaustive
