name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Install CPPCheck
      run: sudo apt-get update && sudo apt-get install cppcheck && cppcheck --version
    - name: Checkout code
      uses: actions/checkout@v2
    - name: make test
      run: make test
    - name: run-tests
      run: make run-tests
    - name: make
      run: make
