name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: debian

    steps:
    - name: Install tools
      run: sudo apt-get install cppcheck
    - name: Collect versions
      run: cppcheck --version
    - name: Checkout code
      uses: actions/checkout@v2
    - name: make test
      run: make test
    - name: run-tests
      run: make run-tests
    - name: make
      run: make
